name: Update crates versions

defaults:
  run:
    shell: bash

on:
  schedule:
    # * is a special character in YAML, needs quoting
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  updateversions:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Retrieve newest versions of dependencies
        run: |
          echo 'cargo_toml<<EOF' >> $GITHUB_ENV
          ./bin/update-crates-versions.sh >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Update Cargo.toml
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "local-registry/Cargo.toml"
          FILE_DATA: "${{env.cargo_toml}}" 
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update crates versions
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update crates versions
          body: |
            Update crates versions

            This is an auto-generated pull request.
      - name: Output PR info
        run: |
          echo "PR Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "PR URL - ${{ steps.cpr.outputs.pull-request-url }}